In [ ]:
#Llama M8b Affinity Score



import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [6]:
#Load the dataset 
df = pd.read_csv('llama_m8b.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 22 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   ExportID                                  17 non-null     object
 1   PenId                                     17 non-null     int64
 2   A1 BtkY72 Cy5 : IsPositiveVerified        17 non-null     bool
 3   A1 BtkY72 Cy5 : Score                     17 non-null     float64
 4   A1 IgG2 FITC : IsPositiveVerified         17 non-null     bool
 5   A1 IgG2 FITC : Score                      17 non-null     float64
 6   A1 Khosta-2 TRED : IsPositiveVerified     17 non-null     bool
 7   A1 Khosta-2 TRED : Score                  17 non-null     float64
 8   A1 SARS-1 DAPI : IsPositiveVerified       17 non-null     bool
 9   A1 SARS-1 DAPI : Score                    17 non-null     float64
 10  A1 Yun11 PE : IsPositiveVerified          17 non-null     bool
 11  A1 Yun11 PE : Score                       17 non-null     float64
 12  A2 _BM4831 PE : IsPositiveVerified        17 non-null     bool
 13  A2 _BM4831 PE : Score                     17 non-null     float64
 14  A2 IgG total CY5 : IsPositiveVerified     17 non-null     bool
 15  A2 IgG total CY5 : Score                  17 non-null     float64
 16  A2 IgG2 FITC : IsPositiveVerified         17 non-null     bool
 17  A2 IgG2 FITC : Score                      17 non-null     float64
 18  A2 SARS-2 beta TRED : IsPositiveVerified  17 non-null     bool
 19  A2 SARS-2 beta TRED : Score               17 non-null     float64
 20  A2 SARS-2 KP3 DAPI : IsPositiveVerified   17 non-null     bool
 21  A2 SARS-2 KP3 DAPI : Score                17 non-null     float64
dtypes: bool(10), float64(10), int64(1), object(1)
memory usage: 1.9+ KB

In [7]:
df.describe()

,PenId,A1 BtkY72 Cy5 : Score,A1 IgG2 FITC : Score,A1 Khosta-2 TRED : Score,A1 SARS-1 DAPI : Score,A1 Yun11 PE : Score,A2 _BM4831 PE : Score,A2 IgG total CY5 : Score,A2 IgG2 FITC : Score,A2 SARS-2 beta TRED : Score,A2 SARS-2 KP3 DAPI : Score
count,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000,17.000000
mean,8423.647059,5.803813,0.961150,6.599683,5.902995,9.697777,9.609297,30.233474,1.280020,30.330747,6.016678
std,5930.088163,3.114175,0.903667,4.037221,6.759491,7.179308,5.363525,10.352296,1.284783,11.216152,4.955530
min,794.000000,0.000000,0.085103,2.372199,0.000000,0.327448,2.266630,20.327020,0.109070,20.014532,0.475600
25%,3652.000000,3.763154,0.183731,3.933736,1.000897,3.501210,5.490494,22.907470,0.140160,23.684322,1.311667
50%,7775.000000,6.625970,0.332554,5.299471,4.114436,9.320222,9.431147,26.846432,0.323601,25.694998,4.396662
75%,13761.000000,8.138821,1.537700,8.119996,6.994422,12.988150,11.847908,34.079760,2.406338,33.110207,10.014246
max,18336.000000,10.571332,2.885190,18.092440,27.229836,27.883556,19.867092,56.373978,3.694074,65.409570,16.203642

In [9]:
df.head()

,ExportID,PenId,A1 BtkY72 Cy5 : IsPositiveVerified,A1 BtkY72 Cy5 : Score,A1 IgG2 FITC : IsPositiveVerified,A1 IgG2 FITC : Score,A1 Khosta-2 TRED : IsPositiveVerified,A1 Khosta-2 TRED : Score,A1 SARS-1 DAPI : IsPositiveVerified,A1 SARS-1 DAPI : Score,...,A2 _BM4831 PE : IsPositiveVerified,A2 _BM4831 PE : Score,A2 IgG total CY5 : IsPositiveVerified,A2 IgG total CY5 : Score,A2 IgG2 FITC : IsPositiveVerified,A2 IgG2 FITC : Score,A2 SARS-2 beta TRED : IsPositiveVerified,A2 SARS-2 beta TRED : Score,A2 SARS-2 KP3 DAPI : IsPositiveVerified,A2 SARS-2 KP3 DAPI : Score
0,P1-B5,7775,True,7.630356,False,0.089087,True,18.092440,False,0.000000,...,True,19.867092,True,33.039967,False,0.167609,True,34.738266,True,12.941354
1,P1-D6,3652,True,3.763154,True,2.201512,False,4.038241,True,11.770784,...,False,2.266630,True,20.577782,True,3.175280,True,24.322641,False,1.194259
2,P1-E6,8429,False,8.138821,True,1.458243,False,7.953848,False,4.327434,...,True,11.847908,True,24.262880,True,2.406338,True,22.748217,True,5.498585
3,P1-F6,9731,True,8.531116,True,1.470881,True,12.049192,False,0.926960,...,True,9.431147,True,24.783136,True,2.623555,True,24.015875,True,8.294621
4,P1-F10,10989,True,6.171044,False,0.145320,True,2.788501,True,3.339382,...,True,10.621079,True,36.674820,False,0.133617,True,36.530490,False,1.311667

In [10]:
#EDA 
id_cols = ['ExportID', 'PenId']

assay_1 = df[id_cols + [c for c in df.columns if c.startswith('A1 ')]]
assay_2 = df[id_cols + [c for c in df.columns if c.startswith('A2 ')]]

In [11]:
assay_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 12 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   ExportID                               17 non-null     object
 1   PenId                                  17 non-null     int64
 2   A1 BtkY72 Cy5 : IsPositiveVerified     17 non-null     bool
 3   A1 BtkY72 Cy5 : Score                  17 non-null     float64
 4   A1 IgG2 FITC : IsPositiveVerified      17 non-null     bool
 5   A1 IgG2 FITC : Score                   17 non-null     float64
 6   A1 Khosta-2 TRED : IsPositiveVerified  17 non-null     bool
 7   A1 Khosta-2 TRED : Score               17 non-null     float64
 8   A1 SARS-1 DAPI : IsPositiveVerified    17 non-null     bool
 9   A1 SARS-1 DAPI : Score                 17 non-null     float64
 10  A1 Yun11 PE : IsPositiveVerified       17 non-null     bool
 11  A1 Yun11 PE : Score                    17 non-null     float64
dtypes: bool(5), float64(5), int64(1), object(1)
memory usage: 1.1+ KB

In [12]:
assay_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 12 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   ExportID                                  17 non-null     object
 1   PenId                                     17 non-null     int64
 2   A2 _BM4831 PE : IsPositiveVerified        17 non-null     bool
 3   A2 _BM4831 PE : Score                     17 non-null     float64
 4   A2 IgG total CY5 : IsPositiveVerified     17 non-null     bool
 5   A2 IgG total CY5 : Score                  17 non-null     float64
 6   A2 IgG2 FITC : IsPositiveVerified         17 non-null     bool
 7   A2 IgG2 FITC : Score                      17 non-null     float64
 8   A2 SARS-2 beta TRED : IsPositiveVerified  17 non-null     bool
 9   A2 SARS-2 beta TRED : Score               17 non-null     float64
 10  A2 SARS-2 KP3 DAPI : IsPositiveVerified   17 non-null     bool
 11  A2 SARS-2 KP3 DAPI : Score                17 non-null     float64
dtypes: bool(5), float64(5), int64(1), object(1)
memory usage: 1.1+ KB

In [15]:
#filtering out igg1 fitc to be in bins 
q1, q2, q3 = np.percentile(assay_1['A1 IgG2 FITC : Score'], [25, 50, 75])
iqr = q3 - q1

In [18]:
assay_1["igg_bin"] = pd.cut(
    assay_1["A1 IgG2 FITC : Score"],
    bins=[-np.inf, q1, q3, np.inf],
    labels=["low", "medium", "high"]) 

assay_1["igg_bin"].value_counts()

/var/folders/gw/tqtm2b315yd232c9f43vnpyr0000gn/T/ipykernel_54747/1256552904.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  assay_1["igg_bin"] = pd.cut(

igg_bin
medium    8
low       5
high      4
Name: count, dtype: int64